### ISSUE TITLE
I can't open the psio_assist.py on windows (python 3 running)

### ISSUE THREAD

**Issue by DarthMotzkus** [logi-26/psio-assist#1]
I can't open the psio_assist.py on windows (python 3 running)

It gave me an error:

D:\Programas\zUteis\PSIO Assist\src>psio_assist.py
Traceback (most recent call last):
  File "D:\Programas\zUteis\PSIO Assist\src\psio_assist.py", line 52, in <module>
    from db import ensure_database_exists, select, extract_game_cover_blob
  File "D:\Programas\zUteis\PSIO Assist\src\db.py", line 11, in <module>
    from fsplit.filesplit import Filesplit
ModuleNotFoundError: No module named 'fsplit.filesplit'

D:\Programas\zUteis\PSIO Assist\src>

Already tried install all dependecies (Fsplit, FileSplit and else).
No juice.
Is anything i am doing wrong?

**Comment by luizbissoni** [comment]
Try this version 'filesplit==3.0.2', but I'm having other issues running it.

**Comment by madocter** [comment]
> Try this version 'filesplit==3.0.2', but I'm having other issues running it.



> I can't open the psio_assist.py on windows (python 3 running)
> 
> It gave me an error:
> 
> D:\Programas\zUteis\PSIO Assist\src>psio_assist.py Traceback (most recent call last): File "D:\Programas\zUteis\PSIO Assist\src\psio_assist.py", line 52, in from db import ensure_database_exists, select, extract_game_cover_blob File "D:\Programas\zUteis\PSIO Assist\src\db.py", line 11, in from fsplit.filesplit import Filesplit ModuleNotFoundError: No module named 'fsplit.filesplit'
> 
> D:\Programas\zUteis\PSIO Assist\src>
> 
> Already tried install all dependecies (Fsplit, FileSplit and else). No juice. Is anything i am doing wrong?

Try following these instructions:
https://github.com/logi-26/psio-assist/issues/2#issuecomment-2302992685

Will update the guide for windows too.

**Comment by logi-26** [comment]
I have added a Windows binary file to make it easier for Windows users to run the application.
