### ISSUE TITLE
This project can´t work without proper instructions, README file is missing important information.

### ISSUE THREAD

**Issue by madocter** [logi-26/psio-assist#2]
Python 3 ... ? 

`pyenv install --list | grep " 3\."
  3.0.1
  3.1.0
  3.1.1
  3.1.2
  3.1.3
  3.1.4
  3.1.5
  3.2.0
  3.2.1
  3.2.2
  3.2.3
  3.2.4
  3.2.5
  3.2.6
  3.3.0
  3.3.1
  3.3.2
  3.3.3
  3.3.4
  3.3.5
  3.3.6
  3.3.7
  3.4.0
  3.4-dev
  3.4.1
  3.4.2
  3.4.3
  3.4.4
  3.4.5
  3.4.6
  3.4.7
  3.4.8
  3.4.9
  3.4.10
  3.5.0
  3.5-dev
  3.5.1
  3.5.2
  3.5.3
  3.5.4
  3.5.5
  3.5.6
  3.5.7
  3.5.8
  3.5.9
  3.5.10
  3.6.0
  3.6-dev
  3.6.1
  3.6.2
  3.6.3
  3.6.4
  3.6.5
  3.6.6
  3.6.7
  3.6.8
  3.6.9
  3.6.10
  3.6.11
  3.6.12
  3.6.13
  3.6.14
  3.6.15
  3.7.0
  3.7-dev
  3.7.1
  3.7.2
  3.7.3
  3.7.4
  3.7.5
  3.7.6
  3.7.7
  3.7.8
  3.7.9
  3.7.10
  3.7.11
  3.7.12
  3.7.13
  3.7.14
  3.7.15
  3.7.16
  3.7.17
  3.8.0
  3.8-dev
  3.8.1
  3.8.2
  3.8.3
  3.8.4
  3.8.5
  3.8.6
  3.8.7
  3.8.8
  3.8.9
  3.8.10
  3.8.11
  3.8.12
  3.8.13
  3.8.14
  3.8.15
  3.8.16
  3.8.17
  3.8.18
  3.8.19
  3.9.0
  3.9-dev
  3.9.1
  3.9.2
  3.9.4
  3.9.5
  3.9.6
  3.9.7
  3.9.8
  3.9.9
  3.9.10
  3.9.11
  3.9.12
  3.9.13
  3.9.14
  3.9.15
  3.9.16
  3.9.17
  3.9.18
  3.9.19
  3.10.0
  3.10-dev
  3.10.1
  3.10.2
  3.10.3
  3.10.4
  3.10.5
  3.10.6
  3.10.7
  3.10.8
  3.10.9
  3.10.10
  3.10.11
  3.10.12
  3.10.13
  3.10.14
  3.11.0
  3.11-dev
  3.11.1
  3.11.2
  3.11.3
  3.11.4
  3.11.5
  3.11.6
  3.11.7
  3.11.8
  3.11.9
  3.12.0
  3.12-dev
  3.12.1
  3.12.2
  3.12.3
  3.12.4
  3.12.5
  3.13.0rc1
  3.13.0rc1t
  3.13-dev
  3.13t-dev
  3.14-dev
  3.14t-dev
`

Which one :) ? 

With 3.11.0 after installing most of dependencies, we will obtain this error :

ModuleNotFoundError: No module named 'fsplit'

https://pypi.org/project/fsplit/

fsplit is based on Python 2.7.

But you said python 3 ... so this module can't be installed, error:

Defaulting to user installation because normal site-packages is not writeable
Collecting fsplit
  Using cached fsplit-1.0.0.tar.gz (7.2 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9c9aw6p8/fsplit_d03bd62e864d4a6e8eaf41f9e49a75ea/setup.py", line 11, in <module>
          from fsplit import __version__
        File "/tmp/pip-install-9c9aw6p8/fsplit_d03bd62e864d4a6e8eaf41f9e49a75ea/fsplit/__init__.py", line 11, in <module>
          from info import __version__ # define __version__ variable
      ModuleNotFoundError: No module named 'info'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

Steps to reproduce this issue:

Install pyenv : https://realpython.com/intro-to-pyenv/

   curl https://pyenv.run | bash  
   // This is depending on your installlation follow the commands that the previous output will tell you.
   export PYENV_ROOT="$HOME/.pyenv" [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
   eval "$(pyenv init -)"
   exec "$SHELL" 
   eval "$(pyenv virtualenv-init -)"
  
Install python I choose this version because this project is from 2 years ago so 2022, and saw in the website the date more or less matches: 3.11 security 2022-10-24  (https://www.python.org/downloads/)

   pyenv install -v 3.11.0
   
Try to launch your "software" but every time requires to install some module so here you can trace:
  
   python3 psio_assist.py 
   pip install pathlib2
   
   python3 psio_assist.py 

   sudo apt-get install python3-tk
   python3 psio_assist.py 
   
   pip install ttkbootstrap

   python3 psio_assist.py
   pip install ImageTk
   
   python3 psio_assist.py
   pip show Pillow
   
   pip install --upgrade Pillow
   python3 psio_assist.py
   
   pip install fsplit  ( Here I got error:  ModuleNotFoundError: No module named 'info' since is for python 2.7
   pip install fsplit3 (This version still for python 2.7)
   python3 psio_assist.py
   
   pip install Filesplit
   python3 psio_assist.py
   
Finaly it can't run:

`Traceback (most recent call last):
  File "/home/miguel/Documents/PROGRAMS/psio-assist-0.2/src/psio_assist.py", line 52, in <module>
    from db import ensure_database_exists, select, extract_game_cover_blob
  File "/home/miguel/Documents/PROGRAMS/psio-assist-0.2/src/db.py", line 11, in <module>
    from fsplit.filesplit import Filesplit
ModuleNotFoundError: No module named 'fsplit'
`

I think you had good intention, but first of all if make public a project you should update the readme with all necessary dependencies modules, etc and put exact versions.

Check Solution in the comment:

**Comment by madocter** [comment]
The solution is to use this specific version of filesplit that is compatible with python 3

pip install filesplit==3.0.2 

https://pypi.org/project/filesplit/3.0.2/

Installing this specific version makes the software able to run.

# Instructions for Windows 7:

Follow steps here: https://github.com/logi-26/psio-assist/issues/3

# Instructions to launch this software: Windows 10 and Linux

**Install pyenv:**  https://realpython.com/intro-to-pyenv/

- `curl https://pyenv.run/ | bash`

// This is depending on your installlation follow the commands that the previous output will tell you.
- `export PYENV_ROOT="$HOME/.pyenv" [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"`
- `eval "$(pyenv init -)"`
- `exec "$SHELL"`
- `eval "$(pyenv virtualenv-init -)"`

**Install python 3.11**
I choose this version because this project is from 2 years ago so 2022, and saw in the website the date more or less matches: 3.11 security 2022-10-24 (https://www.python.org/downloads/)

- `pyenv install -v 3.11.0`

# Install dependencies and modules:

**Install tkinter:**
For Deb (Ubuntu in my case):
- `sudo apt-get install python3-tk`

For RPM
- `sudo dnf install python3-tkinter`

Check how to install in your operating system, Windows should by default have it installed already.




**Update Pillow if necessary:**

- `pip show Pillow`

Must show version: 10.4.0. Otherwise update:

- `pip install --upgrade Pillow`

**Install modules:**
- `pip install pathlib2`
- `pip install ttkbootstrap`
- `pip install ImageTk`
- `pip install filesplit==3.0.2 `

Now you can run the software:
`python3 psio_assist.py`

**Comment by madocter** [comment]
I would make an executable file with pyinstaller, what do you think ?

Install pyinstaller:
pip install pyinstaller

Launch for first time pyinstaller:
python3 -m PyInstaller --onefile --windowed --add-binary "/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0:." psio_assist.py

Add shared libraries to avoid errors: --add-binary "/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0:."

Now you will have file: psio_assist.spec

And in Dist directory the executable file but will not be able to run because hidden imports

Open and edit the file named: psio_assist.spec and add:

- imports:    hiddenimports=['PIL._tkinter_finder', 'PIL.ImageTk'],
- files:         datas=[('data/psio_assist.db', 'data'), ('config', '.')],  

Example:

a = Analysis(
    ['psio_assist.py'],
    pathex=[],
    **binaries=[('/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0', '.')],**
    **datas=[('data/psio_assist.db', 'data'), ('config', '.')],**
    **hiddenimports=['PIL._tkinter_finder', 'PIL.ImageTk'],**
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='psio_assist',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

Save and launch pyinstaller but this time to operate with the spec file:

python3 -m PyInstaller psio_assist.spec

Now you have the executable file, and do not need python or any dependency to execute it.

**Comment by logi-26** [comment]
Better instructions have been added for the Python scripts along with a Windows binary to make it much easier for Windows users.
