### ISSUE TITLE
Not compatible with windows 7

### ISSUE THREAD

**Issue by madocter** [logi-26/psio-assist#3]
# Instructions for Windows 7:

To use this software with "old" windows version:

I install python 3.8.0

https://www.python.org/downloads/release/python-380/

pip install pathlib2
pip install ttkbootstrap
pip install filesplit==3.0.2

pip install fstring
pip install astroid

Then you will get an error because fstring is importing wrong astroid at least in python 3.8

So edit this file: %LocalAppData%\Programs\Python\Python38\Lib\site-packages\fstring\fstring.py

Line 7: replace from astroid.decorators import cachedproperty with from functools import cached_property

Line 43: replace @cachedproperty with @cached_property

**Comment by madocter** [comment]
cue_sheet file_name: Blam! Machinehead (Europe).cue
cue_sheet file_path: F:/xstation/01 CATEGORIAS/ACCION/Blam! Machinehead (Europe)
\Blam! Machinehead (Europe).cue
cue_sheet game_name: Blam! Machinehead (Europe)
Exception in Tkinter callback
Traceback (most recent call last):
File "D:\K5\APPDATA\Local\Programs\Python\Python38\lib\tkinter_init_.py", l
ine 1883, in call
return self.func(*args)
File "psio_assist.py", line 615, in _scan_button_clicked
_parse_game_list()
File "psio_assist.py", line 459, in _parse_game_list
_create_game_list(src_path.get())
File "psio_assist.py", line 424, in _create_game_list
_print_game_details(the_game)
File "psio_assist.py", line 448, in _print_game_details
print(f('number of bin files: {len(bin_files)}'))
File "D:\K5\APPDATA\Local\Programs\Python\Python38\lib\site-packages\fstring\f
string.py", line 103, in str
return self.cached_origin
File "D:\K5\APPDATA\Local\Programs\Python\Python38\lib\functools.py", line 966
, in get
val = self.func(instance)
File "D:\K5\APPDATA\Local\Programs\Python\Python38\lib\site-packages\fstring\f
string.py", line 45, in cached_origin
return self.fstringify()
File "D:\K5\APPDATA\Local\Programs\Python\Python38\lib\site-packages\fstring\f
string.py", line 91, in fstringify
value = eval(indicator, None, frame) # pylint: disable=eval-used
File "", line 1, in
NameError: name 'bin_files' is not defined

Doesn't work I guess is because of this fstring library.

**Comment by logi-26** [comment]
F-string's were introduced in Python 3.6, so I am not sure why they would be causing an issue.
They are also built into Python, so they do not get installed using pip.

Windows 7 has been end-of-life for 5+ years, so it is not worth trying to support it.

If you don't have access to a newer version of Windows I would suggest using a Linux VM or a Raspberry Pi running Linux.
